# Generated by Django 5.0.3 on 2024-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='amount',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='user_name',
            field=models.CharField(default=12),
            preserve_default=False,
        ),
    ]
