# Generated by Django 5.0.3 on 2024-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripecustomer_amount_stripecustomer_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
