# Generated by Django 5.0.3 on 2024-04-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_stripecustomer_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
