# Generated by Django 5.0.3 on 2024-04-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_stripecustomer_end_date_stripecustomer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
