# Generated by Django 5.0.3 on 2024-04-03 05:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tv', 'TV'), ('power_backup', 'Power Backup'), ('fridge', 'Fridge'), ('cook', 'Cook'), ('kitchen', 'Kitchen'), ('parking', 'Parking'), ('wifi', 'Wifi'), ('washing_machine', 'Washing Machine'), ('ac', 'AC')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('attached_washroom', 'Attached Washroom'), ('gated_society', 'Gated Society'), ('park_nearby', 'Park Nearby'), ('market_nearby', 'Market Nearby'), ('no_restriction', 'No Restriction'), ('attached_balcony', 'Attached Balcony'), ('close_to_metro_station', 'Close to Metro Station'), ('newly_built', 'Newly Built'), ('separate_washrooms', 'Separate Washrooms'), ('house_keeping', 'House Keeping'), ('public_transport_nearby', 'Public Transport Nearby'), ('gym_nearby', 'Gym Nearby')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('room', 'Room')], max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('lease_term', models.IntegerField(choices=[(6, '6 months'), (12, '12 months'), (18, '18 months'), (24, '24 months')])),
                ('pet_policy', models.CharField(choices=[('allowed', 'Allowed'), ('not_allowed', 'Not Allowed')], max_length=50)),
                ('smoking_policy', models.CharField(choices=[('allowed', 'Allowed'), ('not_allowed', 'Not Allowed')], max_length=50)),
                ('availability_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('occupancy', models.CharField(choices=[('single', 'Single'), ('shared', 'Shared'), ('any', 'Any')], max_length=50)),
                ('looking_for', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=50)),
                ('approx_rent', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mobile_visible', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(blank=True, to='listing.amenities')),
                ('highlights', models.ManyToManyField(blank=True, to='listing.highlight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
            ],
        ),
    ]
