# Generated by Django 5.0.3 on 2024-04-15 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='approx_rent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lease_term',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
