# Generated by Django 5.0.3 on 2024-04-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_listing_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
