# Generated by Django 5.0.3 on 2024-04-16 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_vacancy',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
