# Generated by Django 5.0.3 on 2024-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_remove_listing_availability_date_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='make_deal',
            field=models.BooleanField(default=False),
        ),
    ]
