# Generated by Django 5.0.3 on 2024-04-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_remove_listing_availability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='confirm_deal',
            field=models.BooleanField(default=False),
        ),
    ]
