# Generated by Django 5.0.3 on 2024-05-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_remove_listing_availability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
