# Generated by Django 5.0.3 on 2024-04-02 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_owl', models.BooleanField(default=False)),
                ('party_lover', models.BooleanField(default=False)),
                ('early_bird', models.BooleanField(default=False)),
                ('pet_lover', models.BooleanField(default=False)),
                ('studious', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('fitness_freak', models.BooleanField(default=False)),
                ('non_alcoholic', models.BooleanField(default=False)),
                ('sporty', models.BooleanField(default=False)),
                ('music_lover', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
