# Generated by Django 5.0.3 on 2024-04-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='non_smoker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='wanderer',
            field=models.BooleanField(default=False),
        ),
    ]
