# Generated by Django 5.0.3 on 2024-04-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userpreference_non_smoker_userpreference_wanderer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DecimalField(decimal_places=0, default=20, max_digits=2),
            preserve_default=False,
        ),
    ]
