# Generated by Django 5.0.3 on 2024-04-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmed_deal',
            field=models.BooleanField(default=False),
        ),
    ]
