# Generated by Django 5.0.3 on 2024-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dxwxpfxgi/image/upload/v1714408857/rijmvo0cqksausiv3ejj.jpg'),
        ),
    ]
