# Generated by Django 5.0.3 on 2024-05-10 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('(^\\+91?\\d{10})|^\\+?\\d{12}$', 'Enter a valid phone number.')]),
        ),
    ]
